#!/usr/bin/env node

var path = require("path");
var ss = require(path.join(__dirname, "../lib/html-snapshots"));

function displayHelp() {
  var pkg = require(path.join(__dirname, "../../package.json"));
  console.log(
    "\n"+
    pkg.name + " Version - " + pkg.version + "\n"+
    "Usage:\n"+
    "  "+pkg.name+" <path to robots.txt> <hostname> <port> <output directory> <selector>\n\n"+
    "Optional arguments:\n"+
    "  7: clean output directory (default is 'false')\n"+
    "  8: timeout (default is 5000 ms)\n"+
    "  9: protocol (default is 'http')\n"+
    "  10: phantomjs (default a global reference to 'phantomjs')\n\n"+
    "For more options, or to use input other than robots.txt, see the readme and use the node module directly.\n"
  );
  return false;
}

var result = false;
// Immediately display help screen if no arguments.
if (process.argv.length < 7) {
  result = displayHelp();
} else {
  result = ss.run({
    //input: "robots",
    source: process.argv[2],
    protocol: (typeof process.argv[9] === "undefined" ? undefined : process.argv[9]),
    hostname: process.argv[3],
    port: process.argv[4],
    outputDirClean: (typeof process.argv[7] === "undefined" ? undefined : process.argv[7]),
    outputDir: process.argv[5],
    selector: process.argv[6],
    timeout: (typeof process.argv[8] === "undefined" ? undefined : process.argv[8]),
    //checkInterval: 250,
    //snapshotScript: "../lib/phantom/snapshotSingle.js",
    phantomjs: (typeof process.argv[10] === "undefined" ? undefined : process.argv[10])
  });
}

process.exit(result ? 0 : -1);