name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        run: npm install -g npm@latest # ensure npm 11.5.1 or later
      - run: npm ci
      - run: npx playwright install
      - name: Lint
        run: npm run lint
      - name: Test
        run: xvfb-run -a npm run test:24
      - name: Publish
        if: ${{ success() }}
        run: npm publish --access public