name: Verify
on:
  pull_request:
    branches: [ master ]

jobs:
  verify:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Lint, Test, And Coverage
      run: npm run lint && xvfb-run -a npm test
    - name: Coverage Upload
      if: ${{ success() }}
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # 2.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
        fail-on-error: false
